/* desktop-assistant client FFI: a C ABI over client-common's UDS Connector. */

#ifndef ADELE_CLIENT_H
#define ADELE_CLIENT_H

/* GENERATED by cbindgen (build.rs) from desktop-assistant-client-ffi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque client handle (see module docs). Created by [`adele_client_connect`],
 * destroyed by [`adele_client_free`].
 */
typedef struct AdeleClient AdeleClient;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Connect to the daemon over UDS. `socket_path` / `minter_socket` may be NULL
 * to use the platform defaults (`$XDG_RUNTIME_DIR/adelie/{sock,mint.sock}`).
 * Returns NULL on failure (bad runtime, daemon unreachable, mint failure).
 *
 * # Safety
 * `socket_path` and `minter_socket` must each be NULL or a valid NUL-terminated
 * C string.
 */
struct AdeleClient *adele_client_connect(const char *socket_path, const char *minter_socket);

/**
 * Start streaming `SignalEvent`s to `cb` as JSON strings. Call once per client.
 * The pump survives daemon restarts (it re-subscribes); after a `disconnected`
 * event the embedder should re-issue [`adele_client_subscribe_conversations`].
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`]. `cb` is invoked
 * from a worker thread with a NUL-terminated JSON string (valid only for that
 * call) plus `user_data`; both must stay valid until [`adele_client_free`].
 */
void adele_client_start_signals(struct AdeleClient *client,
                                void (*cb)(const char*, void*),
                                void *user_data);

/**
 * Set-replace the conversations this client is viewing (live sync). `*_json` is
 * a JSON array of conversation-id strings; `[]` unsubscribes from all. Returns
 * `false` on a bad handle / malformed JSON / dispatch failure.
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`];
 * `conversation_ids_json` must be NULL or a valid NUL-terminated C string.
 */
bool adele_client_subscribe_conversations(struct AdeleClient *client,
                                          const char *conversation_ids_json);

/**
 * Send a prompt; returns the turn `request_id` (the id the streamed events
 * carry) as an owned C string the caller frees with [`adele_string_free`], or
 * NULL on a bad handle / dispatch failure.
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`]; `conversation_id`
 * and `prompt` must be valid NUL-terminated C strings.
 */
char *adele_client_send_prompt(struct AdeleClient *client,
                               const char *conversation_id,
                               const char *prompt);

/**
 * Free a string returned by this library.
 *
 * # Safety
 * `s` must be NULL or a pointer returned by this library and not yet freed.
 */
void adele_string_free(char *s);

/**
 * Disconnect and free the client. Drops the runtime (stopping the pump) and the
 * `Connector` (closing the daemon connection).
 *
 * # Safety
 * `client` must be NULL or a handle from [`adele_client_connect`], not yet freed.
 */
void adele_client_free(struct AdeleClient *client);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ADELE_CLIENT_H */
