/* desktop-assistant client FFI: a C ABI over client-common's UDS Connector. */

#ifndef ADELE_CLIENT_H
#define ADELE_CLIENT_H

/* GENERATED by cbindgen (build.rs) from desktop-assistant-client-ffi. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque client handle (see module docs). Created by [`adele_client_connect`],
 * destroyed by [`adele_client_free`].
 */
typedef struct AdeleClient AdeleClient;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Connect to the daemon over UDS. `socket_path` / `minter_socket` may be NULL
 * to use the platform defaults (`$XDG_RUNTIME_DIR/adelie/{sock,mint.sock}`).
 * Returns NULL on failure (bad runtime, daemon unreachable, mint failure).
 *
 * # Safety
 * `socket_path` and `minter_socket` must each be NULL or a valid NUL-terminated
 * C string.
 */
struct AdeleClient *adele_client_connect(const char *socket_path, const char *minter_socket);

/**
 * Start streaming `SignalEvent`s to `cb` as JSON strings. Call once per client.
 * The pump survives daemon restarts (it re-subscribes); after a `disconnected`
 * event the embedder should re-issue [`adele_client_subscribe_conversations`].
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`]. `cb` is invoked
 * from a worker thread with a NUL-terminated JSON string (valid only for that
 * call) plus `user_data`; both must stay valid until [`adele_client_free`].
 */
void adele_client_start_signals(struct AdeleClient *client,
                                void (*cb)(const char*, void*),
                                void *user_data);

/**
 * Set-replace the conversations this client is viewing (live sync). `*_json` is
 * a JSON array of conversation-id strings; `[]` unsubscribes from all. Returns
 * `false` on a bad handle / malformed JSON / dispatch failure.
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`];
 * `conversation_ids_json` must be NULL or a valid NUL-terminated C string.
 */
bool adele_client_subscribe_conversations(struct AdeleClient *client,
                                          const char *conversation_ids_json);

/**
 * Send a prompt; returns the turn `request_id` (the id the streamed events
 * carry) as an owned C string the caller frees with [`adele_string_free`], or
 * NULL on a bad handle / dispatch failure.
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`]; `conversation_id`
 * and `prompt` must be valid NUL-terminated C strings.
 */
char *adele_client_send_prompt(struct AdeleClient *client,
                               const char *conversation_id,
                               const char *prompt);

/**
 * List the user's conversations as a JSON array of `ConversationSummary` (the
 * daemon's order, newest-first). `include_archived` adds archived ones. Returns
 * NULL on a bad handle / dispatch failure; caller frees with [`adele_string_free`].
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`].
 */
char *adele_client_list_conversations(struct AdeleClient *client, bool include_archived);

/**
 * Fetch a window of a conversation's messages as a JSON `MessagesView`
 * (`{messages, message_count, truncated, ...}`). `tail` caps to the most recent
 * N (`<= 0` = no cap); `after_count` returns only messages past that many
 * already-seen (incremental refresh; `<= 0` = from the start);
 * `include_roles_json` is a JSON array of role names to include (NULL/empty =
 * all roles). Returns NULL on failure; caller frees.
 *
 * # Safety
 * `client` must be live; `conversation_id` a valid C string; `include_roles_json`
 * NULL or a valid C string.
 */
char *adele_client_get_messages(struct AdeleClient *client,
                                const char *conversation_id,
                                int32_t tail,
                                int32_t after_count,
                                const char *include_roles_json);

/**
 * Create a conversation with `title`; returns the new conversation id as an
 * owned C string (caller frees), or NULL on failure.
 *
 * # Safety
 * `client` must be live; `title` a valid C string.
 */
char *adele_client_create_conversation(struct AdeleClient *client, const char *title);

/**
 * Delete a conversation. Returns `false` on a bad handle / failure.
 *
 * # Safety
 * `client` must be live; `conversation_id` a valid C string.
 */
bool adele_client_delete_conversation(struct AdeleClient *client, const char *conversation_id);

/**
 * Send a prompt with an optional per-message model override. `override_json`,
 * when non-NULL, is `{"connection_id":"..","model_id":"..","effort":"low|medium|high"?}`
 * (a malformed value is treated as no override). Returns the turn request-id as
 * an owned C string (caller frees), or NULL on failure.
 *
 * # Safety
 * `client` must be live; `conversation_id` and `prompt` valid C strings;
 * `override_json` NULL or a valid C string.
 */
char *adele_client_send_prompt_with_override(struct AdeleClient *client,
                                             const char *conversation_id,
                                             const char *prompt,
                                             const char *override_json);

/**
 * List available models as a JSON array of `ModelListing`. `connection_id`, when
 * non-NULL, scopes to one connection; `refresh` forces a provider refetch.
 * Returns NULL on failure; caller frees.
 *
 * # Safety
 * `client` must be live; `connection_id` NULL or a valid C string.
 */
char *adele_client_list_available_models(struct AdeleClient *client,
                                         const char *connection_id,
                                         bool refresh);

/**
 * Subscribe this connection to background-task events (`task_started`,
 * `task_progress`, `task_log_appended`, `task_completed`) and
 * `scratchpad_changed`, which then arrive on the signal callback. Returns
 * `false` on a bad handle / failure.
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`].
 */
bool adele_client_subscribe_background_tasks(struct AdeleClient *client);

/**
 * List background tasks as a JSON array of `TaskView`. `include_finished` adds
 * terminal tasks; `limit` caps the count (`<= 0` = no limit). Returns NULL on
 * failure; caller frees.
 *
 * # Safety
 * `client` must be a live handle from [`adele_client_connect`].
 */
char *adele_client_list_background_tasks(struct AdeleClient *client,
                                         bool include_finished,
                                         int32_t limit);

/**
 * Cancel a background task. Returns `false` on a bad handle / failure.
 *
 * # Safety
 * `client` must be live; `task_id` a valid C string.
 */
bool adele_client_cancel_background_task(struct AdeleClient *client, const char *task_id);

/**
 * Fetch a page of a background task's logs as JSON
 * (`{"entries":[TaskLogEntry...],"next_seq":N}`). `after_seq` skips already-seen
 * entries (`< 0` = from oldest); `limit` caps the page (`<= 0` = server
 * default). Returns NULL on failure; caller frees.
 *
 * # Safety
 * `client` must be live; `task_id` a valid C string.
 */
char *adele_client_get_background_task_logs(struct AdeleClient *client,
                                            const char *task_id,
                                            int64_t after_seq,
                                            int32_t limit);

/**
 * Free a string returned by this library.
 *
 * # Safety
 * `s` must be NULL or a pointer returned by this library and not yet freed.
 */
void adele_string_free(char *s);

/**
 * Disconnect and free the client. Drops the runtime (stopping the pump) and the
 * `Connector` (closing the daemon connection).
 *
 * # Safety
 * `client` must be NULL or a handle from [`adele_client_connect`], not yet freed.
 */
void adele_client_free(struct AdeleClient *client);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* ADELE_CLIENT_H */
