//! HS256 JWT primitives shared by the daemon and the JWT minter.
//!
//! This crate is deliberately small and policy-free. It exposes the wire
//! format ([`Claims`]), the codec ([`encode`], [`decode`], [`decode_with`]),
//! and atomic file IO for the signing key ([`read_signing_key_at`],
//! [`write_signing_key_at`], [`ensure_signing_key_at`]). Callers — the
//! daemon today, the minter next — pick their own issuer, audience, TTL,
//! and key path.
//!
//! The signing key is generated as 64 hex chars (two UUIDv4 simples joined)
//! when [`ensure_signing_key_at`] runs against an empty path, written
//! atomically with mode 0600 under a 0700 parent dir. This matches the
//! convention the daemon's secret store has used since #41 so a key
//! generated by either side validates on the other.

use std::path::{Path, PathBuf};

use anyhow::anyhow;
use jsonwebtoken::{Algorithm, DecodingKey, EncodingKey, Header, Validation};
use serde::{Deserialize, Serialize};

/// HS256 JWT claim payload.
///
/// Fields are public so callers can construct claims directly and tests
/// can mutate fields to forge tokens. The wire format is fixed by
/// `serde` field names; renaming any field is a breaking change to
/// existing tokens.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Claims {
    pub iss: String,
    pub sub: String,
    pub aud: String,
    pub exp: u64,
    pub iat: u64,
    pub nbf: u64,
    pub jti: String,
}

/// Encode `claims` as an HS256 JWT signed with `signing_key`.
pub fn encode(claims: &Claims, signing_key: &str) -> anyhow::Result<String> {
    jsonwebtoken::encode(
        &Header::new(Algorithm::HS256),
        claims,
        &EncodingKey::from_secret(signing_key.as_bytes()),
    )
    .map_err(|error| anyhow!("failed to encode jwt: {error}"))
}

/// Decode and verify `token` against `signing_key` using `validation`.
///
/// Callers control issuer/audience/leeway via the supplied [`Validation`].
/// Unlike [`decode`] there's no implicit issuer/audience policy — the
/// daemon and minter own that.
pub fn decode_with(
    token: &str,
    signing_key: &str,
    validation: &Validation,
) -> anyhow::Result<Claims> {
    let decoded = jsonwebtoken::decode::<Claims>(
        token,
        &DecodingKey::from_secret(signing_key.as_bytes()),
        validation,
    )
    .map_err(|error| anyhow!("failed to decode jwt: {error}"))?;
    Ok(decoded.claims)
}

/// Decode `token` against `signing_key`, requiring `expected_issuer` and
/// `expected_audience`. Validates `exp`/`nbf` and the HS256 signature.
///
/// This is the convenience that covers the common case; for anything
/// fancier (clock skew leeway, multiple acceptable audiences, no audience
/// check) build your own [`Validation`] and call [`decode_with`].
pub fn decode(
    token: &str,
    signing_key: &str,
    expected_issuer: &str,
    expected_audience: &str,
) -> anyhow::Result<Claims> {
    let mut validation = Validation::new(Algorithm::HS256);
    validation.validate_exp = true;
    validation.set_issuer(&[expected_issuer]);
    validation.set_audience(&[expected_audience]);
    decode_with(token, signing_key, &validation)
}

/// Read the HS256 signing key from `path`, returning `None` if the file
/// is missing or unreadable. Trailing whitespace is trimmed; an empty
/// file is treated as missing.
pub fn read_signing_key_at(path: &Path) -> Option<String> {
    let raw = std::fs::read_to_string(path).ok()?;
    let trimmed = raw.trim().to_string();
    if trimmed.is_empty() { None } else { Some(trimmed) }
}

/// Atomically write `value` to `path` with mode 0600 (Unix). The parent
/// directory is created if missing and tightened to 0700.
pub fn write_signing_key_at(path: &Path, value: &str) -> anyhow::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|error| {
            anyhow!(
                "failed to create signing-key parent dir {}: {error}",
                parent.display()
            )
        })?;

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = std::fs::set_permissions(parent, std::fs::Permissions::from_mode(0o700));
        }
    }

    #[cfg(unix)]
    {
        use std::io::Write;
        use std::os::unix::fs::OpenOptionsExt;
        let mut file = std::fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(path)
            .map_err(|error| {
                anyhow!("failed to write signing key {}: {error}", path.display())
            })?;
        file.write_all(value.as_bytes()).map_err(|error| {
            anyhow!("failed to write signing key {}: {error}", path.display())
        })?;
    }

    #[cfg(not(unix))]
    {
        std::fs::write(path, value).map_err(|error| {
            anyhow!("failed to write signing key {}: {error}", path.display())
        })?;
    }

    Ok(())
}

/// Read the signing key from `path` if it exists, otherwise generate a
/// fresh 64-hex-char key, persist it, and return the new value.
///
/// A read of a present file always wins; only the first call against an
/// empty path generates. This makes it safe for two processes (daemon
/// and minter) to call concurrently — both observe the same key as soon
/// as one finishes the write.
pub fn ensure_signing_key_at(path: &Path) -> anyhow::Result<String> {
    if let Some(existing) = read_signing_key_at(path) {
        return Ok(existing);
    }

    let generated = generate_signing_key();
    write_signing_key_at(path, &generated)?;
    Ok(generated)
}

fn generate_signing_key() -> String {
    // 64 hex chars from two UUIDv4 simples gives ~256 bits of entropy,
    // which is plenty for an HS256 HMAC secret.
    format!(
        "{}{}",
        uuid::Uuid::new_v4().simple(),
        uuid::Uuid::new_v4().simple()
    )
}

/// Convenience: returns the conventional signing-key path for desktop
/// installs (`$XDG_DATA_HOME/desktop-assistant/secrets/ws_jwt_hs256_signing_key`).
///
/// Server deployments should ignore this and pick a deployment-appropriate
/// path. The daemon uses this default; the minter takes a `--signing-key`
/// argument and falls back to this when unset.
pub fn default_signing_key_path() -> PathBuf {
    let data_home = std::env::var("XDG_DATA_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            PathBuf::from(std::env::var("HOME").unwrap_or_else(|_| ".".to_string()))
                .join(".local")
                .join("share")
        });
    data_home
        .join("desktop-assistant")
        .join("secrets")
        .join("ws_jwt_hs256_signing_key")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn make_claims(now: u64) -> Claims {
        Claims {
            iss: "test-iss".into(),
            sub: "alice".into(),
            aud: "test-aud".into(),
            exp: now + 600,
            iat: now,
            nbf: now.saturating_sub(1),
            jti: "test-jti".into(),
        }
    }

    #[test]
    fn round_trip_encode_decode() {
        let key = "deadbeef".repeat(8);
        let claims = make_claims(unix_now());
        let token = encode(&claims, &key).unwrap();
        let decoded = decode(&token, &key, "test-iss", "test-aud").unwrap();
        assert_eq!(decoded.sub, "alice");
        assert_eq!(decoded.iss, "test-iss");
        assert_eq!(decoded.aud, "test-aud");
    }

    #[test]
    fn rejects_wrong_issuer() {
        let key = "deadbeef".repeat(8);
        let claims = make_claims(unix_now());
        let token = encode(&claims, &key).unwrap();
        let err = decode(&token, &key, "other-iss", "test-aud").unwrap_err();
        assert!(err.to_string().to_lowercase().contains("decode"));
    }

    #[test]
    fn rejects_wrong_audience() {
        let key = "deadbeef".repeat(8);
        let claims = make_claims(unix_now());
        let token = encode(&claims, &key).unwrap();
        let err = decode(&token, &key, "test-iss", "other-aud").unwrap_err();
        assert!(err.to_string().to_lowercase().contains("decode"));
    }

    #[test]
    fn rejects_wrong_signing_key() {
        let claims = make_claims(unix_now());
        let token = encode(&claims, "key-a").unwrap();
        decode(&token, "key-b", "test-iss", "test-aud").unwrap_err();
    }

    #[test]
    fn rejects_expired_token() {
        // jsonwebtoken's default Validation has a 60s leeway, so a token
        // that expired ~minute ago is still considered valid. Push exp
        // well past the leeway window.
        let key = "deadbeef".repeat(8);
        let now = unix_now();
        let mut claims = make_claims(now);
        claims.iat = now.saturating_sub(7200);
        claims.nbf = now.saturating_sub(7200);
        claims.exp = now.saturating_sub(3600);
        let token = encode(&claims, &key).unwrap();
        decode(&token, &key, "test-iss", "test-aud").unwrap_err();
    }

    #[test]
    fn ensure_generates_then_reads_same_key() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("nested").join("key");
        let first = ensure_signing_key_at(&path).unwrap();
        let second = ensure_signing_key_at(&path).unwrap();
        assert_eq!(first, second);
        assert_eq!(first.len(), 64);
        assert!(first.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn ensure_creates_parent_dir() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("a").join("b").join("c").join("key");
        ensure_signing_key_at(&path).unwrap();
        assert!(path.exists());
    }

    #[cfg(unix)]
    #[test]
    fn writes_key_file_with_0600_perms() {
        use std::os::unix::fs::PermissionsExt;
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("key");
        ensure_signing_key_at(&path).unwrap();
        let mode = std::fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o600);
    }

    #[test]
    fn read_returns_none_for_missing_file() {
        let dir = TempDir::new().unwrap();
        assert!(read_signing_key_at(&dir.path().join("nope")).is_none());
    }

    #[test]
    fn read_trims_trailing_whitespace() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("k");
        std::fs::write(&path, "abc\n\n  ").unwrap();
        assert_eq!(read_signing_key_at(&path).as_deref(), Some("abc"));
    }

    #[test]
    fn read_treats_empty_file_as_missing() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("k");
        std::fs::write(&path, "  \n").unwrap();
        assert!(read_signing_key_at(&path).is_none());
    }

    #[test]
    fn token_signed_by_minter_validates_in_daemon() {
        // The whole point of extracting this crate: a token issued in
        // one process (the future minter, in tests just a fresh key dir)
        // validates against the same key file from a different caller
        // (the daemon's shim).
        let dir = TempDir::new().unwrap();
        let key_path = dir.path().join("key");
        let key_a = ensure_signing_key_at(&key_path).unwrap();

        let now = unix_now();
        let claims = Claims {
            iss: "org.desktopAssistant.local".into(),
            sub: "dave".into(),
            aud: "desktop-assistant-ws".into(),
            exp: now + 900,
            iat: now,
            nbf: now.saturating_sub(1),
            jti: uuid::Uuid::new_v4().to_string(),
        };
        let token = encode(&claims, &key_a).unwrap();

        // Different process reads the same path.
        let key_b = read_signing_key_at(&key_path).unwrap();
        assert_eq!(key_a, key_b);
        let decoded = decode(
            &token,
            &key_b,
            "org.desktopAssistant.local",
            "desktop-assistant-ws",
        )
        .unwrap();
        assert_eq!(decoded.sub, "dave");
    }

    fn unix_now() -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs()
    }
}
